packages:
  - packages/**
  - playground/**

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - lmdb
  - msgpackr-extract
  - rolldown
  - sharp
  - unrs-resolver

overrides:
  vue-tsc: '3.1.5' # https://github.com/vuejs/language-tools/issues/5810
