import type { Report } from '../report.js';
import type { Resource } from '../types.js';

export function updateInputs( report: Report ): Array<Resource> {
	// Get all resources that were generated by the bundler
	const assets = report.resources
		.filter( resource => resource.kind === 'asset' )
		.map( resource => resource.name );
	
	// Get all resources that are used by the assets
	const usedResources = report.connections
		.filter( connection => assets.includes( connection.source ) )
		.map( connection => connection.target );

	// Remove filesystem resources that are not used by the assets
	return report.resources.filter( resource => resource.kind !== 'filesystem' || usedResources.includes( resource.name ) );
}
