import type { Report } from '../report.js';

export function updateInputs( report: Report ): void {
	// Get all resources that were generated by the bundler
	const assets = report.resources
		.filter( resource => resource.kind === 'asset' )
		.map( resource => resource.name );
	
	// Get all resources that are used by the assets
	const usedResources = report.edges
		.filter( edge => assets.includes( edge.source ) )
		.map( edge => edge.target );

	// Remove filesystem resources that are not used by the assets
	report.resources = report.resources.filter( resource => resource.kind !== 'filesystem' || usedResources.includes( resource.name ) );
}
