<template>
	<div class="flex max-w-7xl flex-col">
		<h2 class="text-2xl font-bold">Build summary</h2>

		<p class="mt-4 text-gray-600">Quick summary of all assets generated by the bundler.</p>

		<hr class="mt-4 mb-6 border-gray-100" />

		<Alert
			v-if="!hasChunks"
			variant="warning"
		>
			<template #header>
				<p>Have you enabled source maps in the bundler configuration?</p>
			</template>

			<template #body>
				<p>
					It appears that source map generation was not enabled, causing the report to omit a lot of information.
					<span class="font-bold">Please enable source maps and rebuild your project.</span>
				</p>

				<p class="mt-2">
					For more information, refer to the
					<a
						class="underline"
						href="https://sonda.dev/"
						>documentation</a
					>.
				</p>
			</template>
		</Alert>

		<h3 class="mb-4 text-xl font-bold">Assets</h3>

		<div class="grid grid-cols-3 gap-2">
			<a
				v-for="type in types"
				:key="type.type"
				:disabled="type.size === 0"
				:class="[
					type.type === 'all' ? 'xl:col-span-3' : 'xl:col-span-1',
					type.size === 0 ? 'pointer-events-none cursor-none opacity-50' : 'hover:bg-gray-50'
				]"
				:href="type.href"
				:tabindex="type.size === 0 ? -1 : 0"
				class="col-span-3 flex flex-col rounded-lg border border-gray-300 p-4 shadow-xs outline-hidden transition-colors duration-150 focus:border-gray-500 focus:ring focus:ring-gray-500"
			>
				<div class="flex items-start justify-between">
					<p class="font-semibold text-gray-500">{{ type.label }}</p>
					<component
						:is="type.icon"
						:size="18"
						class="text-gray-300"
					/>
				</div>

				<p class="mt-1 text-xl">
					{{ formatSize(type.size) }}
					<span class="text-gray-400">({{ type.count }})</span>
				</p>
			</a>
		</div>
	</div>
</template>

<script setup lang="ts">
import { computed, type Component } from 'vue';
import { router } from '@/router.js';
import { getAssets, report } from '@/report.js';
import { formatSize } from '@/format.js';
import Alert from '@/components/common/Alert.vue';
import IconBox from '@icon/Box.vue';
import IconCode from '@icon/Code.vue';
import IconBrush from '@icon/Brush.vue';
import IconImage from '@icon/Image.vue';
import IconTypeOutline from '@icon/TypeOutline.vue';
import IconComponent from '@icon/Component.vue';
import IconFileQuestion from '@icon/FileQuestion.vue';
import type { FileType } from 'sonda';

interface AssetType {
	type: FileType | 'all';
	label: string;
	icon: Component;
	href: string;
	size: number;
	count: number;
}

const ASSET_TYPES: Record<FileType | 'all', AssetType> = {
	all: {
		type: 'all',
		label: 'Total size',
		icon: IconBox,
		href: router.getUrl('treemap'),
		size: 0,
		count: 0
	},
	script: {
		type: 'script',
		label: 'JavaScript',
		icon: IconCode,
		href: router.getUrl('treemap', { types: 'script' }),
		size: 0,
		count: 0
	},
	style: {
		type: 'style',
		label: 'CSS',
		icon: IconBrush,
		href: router.getUrl('treemap', { types: 'style' }),
		size: 0,
		count: 0
	},
	image: {
		type: 'image',
		label: 'Image',
		icon: IconImage,
		href: router.getUrl('treemap', { types: 'image' }),
		size: 0,
		count: 0
	},
	font: {
		type: 'font',
		label: 'Font',
		icon: IconTypeOutline,
		href: router.getUrl('treemap', { types: 'font' }),
		size: 0,
		count: 0
	},
	component: {
		type: 'component',
		label: 'Component',
		icon: IconComponent,
		href: router.getUrl('treemap', { types: 'component' }),
		size: 0,
		count: 0
	},
	other: {
		type: 'other',
		label: 'Other',
		icon: IconFileQuestion,
		href: router.getUrl('treemap', { types: 'other' }),
		size: 0,
		count: 0
	}
};

const types = computed(() => {
	const countedTypes = Object.values(getAssets()).reduce((acc, asset) => {
		acc[asset.type].size += asset.uncompressed;
		acc[asset.type].count += 1;

		acc.all.size += asset.uncompressed;
		acc.all.count += 1;

		return acc;
	}, ASSET_TYPES);

	return Object.values(countedTypes);
});

const hasChunks = computed(() => report.resources.some(resource => resource.kind === 'chunk'));
</script>
