<template>
	<div class="max-w-7xl flex flex-col">
		<h2 class="text-2xl font-bold">{{ formattedName }}</h2>

		<p class="text-gray-500 mt-4">
			Details of the output assets generated by the bundler.
		</p>

		<hr class="mt-4 mb-6 border-gray-100">

		<div class="flex flex-col mb-4">
			<Tabs
				v-model="activeTab"
				:options="TABS"
			>
				<template #details>
					<Details :name="name" />
				</template>

				<template #dependencies>
					<Dependencies :name="name" :inputs="inputs" />
				</template>

				<template #inputs>
					<Inputs :name="name" :inputs="inputs" />
				</template>
			</Tabs>
		</div>
	</div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { router } from '@/router.js';
import { getChunks } from '@/report.js';
import { formatPath } from '@/format.js';
import Tabs from '@/components/common/Tabs.vue';
import Details from '@/components/assets/Details.vue';
import Dependencies from '@/components/assets/Dependencies.vue';
import Inputs from '@/components/assets/Inputs.vue';

const TABS = [
	{ label: 'Details', value: 'details' },
	{ label: 'Dependencies', value: 'dependencies' },
	{ label: 'Inputs', value: 'inputs' }
];

const activeTab = computed( router.computedQuery( 'tab', TABS[ 0 ].value ) );
const name = computed( () => router.query.item );
const formattedName = computed( () => formatPath( name.value ) );

// Inputs
const inputs = computed( () => {
	return getChunks( name.value )
		.filter( chunk => chunk.name !== '[unassigned]' )
		.map( chunk => chunk.name )
		.toSorted();
} );
</script>
