<template>
	<div class="flex max-w-7xl flex-col">
		<template v-if="asset">
			<h2 class="text-2xl font-bold">{{ formattedName }}</h2>

			<p class="mt-4 text-gray-500">Details of the output assets generated by the bundler.</p>

			<hr class="mt-4 mb-6 border-gray-100" />

			<div class="mb-4 flex flex-col">
				<Details :name />

				<Dependencies
					:name
					:inputs="inputs"
					class="mt-4"
				/>

				<Inputs
					:name
					:inputs="inputs"
					class="mt-4"
				/>
			</div>
		</template>

		<template v-else>
			<Alert variant="error">
				<template #header>
					<p>The asset does not exist</p>
				</template>

				<template #body>
					<p>
						The asset you are looking for does not exist. Go back to the
						<a
							:href="router.getUrl('assets')"
							class="underline"
							>Assets</a
						>
						page to see all the available assets.
					</p>
				</template>
			</Alert>
		</template>
	</div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { router } from '@/router.js';
import { getAssetResource, getChunks } from '@/report.js';
import { formatPath } from '@/format.js';
import Alert from '@/components/common/Alert.vue';
import Details from '@/components/sections/Assets/Details.vue';
import Dependencies from '@/components/sections/Assets/Dependencies.vue';
import Inputs from '@/components/sections/Assets/Inputs.vue';

const name = computed(() => router.query.item);
const asset = computed(() => getAssetResource(name.value));
const formattedName = computed(() => formatPath(name.value));

// Inputs
const inputs = computed(() => {
	return getChunks(name.value)
		.filter(chunk => chunk.name !== '[unassigned]')
		.map(chunk => chunk.name)
		.toSorted();
});
</script>
