<template>
	<div class="max-w-7xl flex flex-col">
		<h2 class="text-2xl font-bold">{{ formattedName }}</h2>

		<p class="text-gray-500 mt-4">
			Details of the output assets generated by the bundler.
		</p>

		<hr class="mt-4 mb-6 border-gray-100">

		<div class="flex flex-col mb-4">
			<Details :name />

			<Dependencies
				:name
				:inputs="inputs"
				class="mt-4"
			/>

			<Inputs
				:name
				:inputs="inputs"
				class="mt-4"
			/>
		</div>
	</div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { router } from '@/router.js';
import { getChunks } from '@/report.js';
import { formatPath } from '@/format.js';
import Details from '@/components/sections/Assets/Details.vue';
import Dependencies from '@/components/sections/Assets/Dependencies.vue';
import Inputs from '@/components/sections/Assets/Inputs.vue';

const name = computed( () => router.query.item );
const formattedName = computed( () => formatPath( name.value ) );

// Inputs
const inputs = computed( () => {
	return getChunks( name.value )
		.filter( chunk => chunk.name !== '[unassigned]' )
		.map( chunk => chunk.name )
		.toSorted();
} );
</script>
