<template>
	<div
		v-if="isDragging"
		class="pointer-events-none fixed inset-0 z-40 flex items-center justify-center bg-white/70 backdrop-blur-sm"
	>
		<div class="rounded-xl border-2 border-dashed border-gray-400 bg-white px-8 py-6 text-center shadow-sm">
			<p class="text-lg font-semibold text-gray-900">Drop Sonda JSON report</p>
			<p class="mt-1 text-sm text-gray-600">Release anywhere to upload</p>
		</div>
	</div>

	<div class="flex min-h-screen w-full items-center justify-center bg-white p-6">
		<div class="w-full max-w-2xl p-6">
			<h1 class="text-2xl font-medium text-gray-900">Analyze Sonda JSON report</h1>

			<p class="mt-4 text-base text-gray-600">
				Upload a <code class="mx-0.5 rounded bg-gray-100 px-1 py-px">.json</code> report generated by Sonda and explore
				it in your browser.
				<span class="font-semibold">Everything is processed locally and data stays on your machine.</span>
			</p>

			<label
				:class="[
					isDragging
						? 'border-gray-400 bg-gray-100'
						: 'border-gray-300 bg-white hover:border-gray-400 hover:bg-gray-50',
					isLoading && 'pointer-events-none opacity-70'
				]"
				class="mt-12 flex cursor-pointer flex-col items-center justify-center rounded-xl border-2 border-dashed px-6 py-10 text-center transition-colors duration-150"
			>
				<input
					type="file"
					accept="application/json,.json"
					class="sr-only"
					:disabled="isLoading"
					@change="onFileSelected"
				/>

				<div class="flex items-center justify-center rounded-full text-gray-400">
					<IconFileInput :size="42" />
				</div>

				<template v-if="!isLoading">
					<span class="mt-4 text-base text-gray-600">Drag and drop anywhere, or click this area to browse.</span>

					<span
						class="mt-3 rounded-lg border border-gray-300 bg-gray-50 px-3 py-1.5 text-sm font-medium text-gray-700 shadow-xs"
					>
						Select file
					</span>
				</template>

				<span
					v-else
					class="mt-3 text-gray-500"
				>
					Loading {{ selectedFile }}...
				</span>
			</label>

			<form
				class="mt-12"
				@submit.prevent="onUrlSubmit"
			>
				<p class="text-base font-medium text-gray-700">Or load report from URL</p>

				<div class="mt-2 flex flex-col gap-2 sm:flex-row">
					<input
						v-model="reportUrl"
						:disabled="isLoading"
						type="url"
						required
						placeholder="Enter report URL"
						class="h-8 w-full rounded-lg border border-gray-300 bg-white px-3 text-sm text-gray-900 shadow-xs outline-hidden transition-colors duration-150 placeholder:text-gray-500 focus:border-gray-500 focus:ring focus:ring-gray-500 disabled:cursor-not-allowed disabled:opacity-50"
					/>

					<BaseButton
						type="submit"
						:disabled="isLoading"
						class="px-4 text-gray-700"
					>
						Load
					</BaseButton>
				</div>
			</form>

			<Alert
				v-if="!isTrustedUrl"
				class="mt-4"
				variant="warning"
			>
				<template #header>Unverified report URL</template>
				<template #body>This URL comes from an unverified host. Only load it if you trust the report source.</template>
			</Alert>

			<div class="mt-16 rounded-lg border border-gray-200 bg-gray-50 p-6">
				<div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
					<div>
						<p class="text-sm font-medium text-gray-900">Open the demo report</p>
						<p class="text-sm text-gray-500">Use sample data to explore the interface and functionality.</p>
					</div>

					<BaseButton
						type="button"
						:disabled="isLoading"
						active
						class="px-4"
						@click="onLoadDemo"
					>
						Load demo
					</BaseButton>
				</div>
			</div>

			<Alert
				v-if="errorMessage"
				class="mt-4 mb-0"
				variant="error"
			>
				<template #header>Load failed</template>
				<template #body>{{ errorMessage }}</template>
			</Alert>
		</div>
	</div>
</template>

<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref, computed } from 'vue';
import { router } from '@/router.js';
import { loadReportFromJson, loadReportFromUrl } from '@/report.js';
import IconFileInput from '@icon/FileInput.vue';
import Alert from '@/components/common/Alert.vue';
import BaseButton from '@components/common/Button.vue';

const errorMessage = ref('');
const isLoading = ref(false);
const isDragging = ref(false);
const dragDepth = ref(0);
const selectedFile = ref('');
const demoReportUrl = new URL('/sample_data.json', window.location.origin).href;
const reportUrl = computed(router.computedQuery('reportUrl', ''));

const isTrustedUrl = computed(() => {
	if (!reportUrl.value) {
		return true;
	}

	try {
		const url = new URL(reportUrl.value);
		return url.origin === window.location.origin;
	} catch {
		return false;
	}
});

async function processFile(file: File | undefined): Promise<void> {
	if (!file) {
		return;
	}

	if (!file.name.toLowerCase().endsWith('.json')) {
		errorMessage.value = 'Only JSON reports are supported. Please select a `.json` file.';
		return;
	}

	selectedFile.value = file.name;
	errorMessage.value = '';
	isLoading.value = true;

	try {
		loadReportFromJson(await file.text());
		router.navigate('');
	} catch (error: any) {
		errorMessage.value = error.message ?? 'Failed to load report.';
	} finally {
		isLoading.value = false;
	}
}

async function processUrl(url: string): Promise<void> {
	const trimmedUrl = url.trim();

	if (!trimmedUrl) {
		errorMessage.value = 'Please enter a report URL.';
		return;
	}

	selectedFile.value = trimmedUrl;
	errorMessage.value = '';
	isLoading.value = true;

	try {
		await loadReportFromUrl(trimmedUrl);
		router.navigate('');
	} catch (error: any) {
		errorMessage.value = error.message ?? 'Failed to load report.';
	} finally {
		isLoading.value = false;
	}
}

async function onFileSelected(event: Event): Promise<void> {
	const target = event.target as HTMLInputElement;

	await processFile(target.files?.[0]);
	target.value = '';
}

async function onUrlSubmit(): Promise<void> {
	await processUrl(reportUrl.value);
}

async function onLoadDemo(): Promise<void> {
	await processUrl(demoReportUrl);
}

function isFileDrag(event: DragEvent): boolean {
	const types = event.dataTransfer?.types;

	return Boolean(types && Array.from(types).includes('Files'));
}

function onWindowDragEnter(event: DragEvent): void {
	if (!isFileDrag(event) || isLoading.value) {
		return;
	}

	event.preventDefault();

	dragDepth.value += 1;
	isDragging.value = true;
}

function onWindowDragOver(event: DragEvent): void {
	if (!isFileDrag(event) || isLoading.value) {
		return;
	}

	event.preventDefault();
}

function onWindowDragLeave(event: DragEvent): void {
	if (!isFileDrag(event)) {
		return;
	}

	event.preventDefault();

	dragDepth.value = Math.max(0, dragDepth.value - 1);

	if (dragDepth.value === 0) {
		isDragging.value = false;
	}
}

async function onWindowDrop(event: DragEvent): Promise<void> {
	if (!isFileDrag(event)) {
		return;
	}

	event.preventDefault();

	dragDepth.value = 0;
	isDragging.value = false;

	if (isLoading.value) {
		return;
	}

	await processFile(event.dataTransfer?.files?.[0]);
}

onMounted(() => {
	window.addEventListener('dragenter', onWindowDragEnter);
	window.addEventListener('dragover', onWindowDragOver);
	window.addEventListener('dragleave', onWindowDragLeave);
	window.addEventListener('drop', onWindowDrop);
});

onBeforeUnmount(() => {
	window.removeEventListener('dragenter', onWindowDragEnter);
	window.removeEventListener('dragover', onWindowDragOver);
	window.removeEventListener('dragleave', onWindowDragLeave);
	window.removeEventListener('drop', onWindowDrop);
});
</script>
