<template>
	<div class="max-w-7xl flex flex-col">
		<h2 class="text-2xl font-bold">Build summary</h2>

		<p class="text-gray-600 mt-4">
			Quick summary of all assets generated by the bundler.
		</p>

		<hr class="mt-4 mb-6 border-gray-100">

		<h3 class="text-xl font-bold mb-4">Assets</h3>

		<div class="grid grid-cols-3 gap-2">
			<a
				v-for="type in types"
				:key="type.type"
				:disabled="type.size === 0"
				:class="[
					type.type === 'all' ? 'xl:col-span-3' : 'xl:col-span-1',
					type.size === 0 ? 'opacity-50 pointer-events-none cursor-none' : 'hover:bg-gray-50'
				]"
				:href="type.href"
				class="p-4 col-span-3 flex flex-col border border-gray-300 rounded-lg shadow-xs transition-colors duration-150"
			>
				<div class="flex items-start justify-between">
					<p class="text-gray-500 font-semibold">{{ type.label }}</p>
					<component :is="type.icon" :size="18" class="text-gray-300" />
				</div>

				<p class="text-xl mt-1">
					{{ formatSize( type.size ) }}
					<span class="text-gray-400">({{ type.count }})</span>
				</p>
			</a>
		</div>
	</div>
</template>

<script setup lang="ts">
import { computed, type Component } from 'vue';
import { router } from '@/router.js';
import { getAssets } from '@/report.js';
import { formatSize } from '@/format.js';
import IconBox from '@icon/Box.vue';
import IconCode from '@icon/Code.vue';
import IconBrush from '@icon/Brush.vue';
import IconImage from '@icon/Image.vue';
import IconTypeOutline from '@icon/TypeOutline.vue';
import IconComponent from '@icon/Component.vue';
import IconFileQuestion from '@icon/FileQuestion.vue';
import type { FileType } from 'sonda';

interface AssetType {
	type: FileType | 'all';
	label: string;
	icon: Component;
	href: string;
	size: number;
	count: number;
}

const ASSET_TYPES: Record<FileType | 'all', AssetType> = {
	all: {
		type: 'all',
		label: 'Total size',
		icon: IconBox,
		href: router.getUrl( 'assets' ),
		size: 0,
		count: 0
	},
	script: {
		type: 'script',
		label: 'JavaScript',
		icon: IconCode,
		href: router.getUrl( 'assets', { types: 'script' } ),
		size: 0,
		count: 0
	},
	style:{
		type: 'style',
		label: 'CSS',
		icon: IconBrush,
		href: router.getUrl( 'assets', { types: 'style' } ),
		size: 0,
		count: 0
	},
	image: {
		type: 'image',
		label: 'Image',
		icon: IconImage,
		href: router.getUrl( 'assets', { types: 'image' } ),
		size: 0,
		count: 0
	},
	font:{
		type: 'font',
		label: 'Font',
		icon: IconTypeOutline,
		href: router.getUrl( 'assets', { types: 'font' } ),
		size: 0,
		count: 0
	},
	component:{
		type: 'component',
		label: 'Component',
		icon: IconComponent,
		href: router.getUrl( 'assets', { types: 'component' } ),
		size: 0,
		count: 0
	},
	other:{
		type: 'other',
		label: 'Other',
		icon: IconFileQuestion,
		href: router.getUrl( 'assets', { types: 'other' } ),
		size: 0,
		count: 0
	}
};

const types = computed( () => {
	const countedTypes = Object
		.values( getAssets() )
		.reduce( ( acc, asset ) => {
			acc[ asset.type ].size += asset.uncompressed;
			acc[ asset.type ].count += 1;

			acc.all.size += asset.uncompressed;
			acc.all.count += 1;

			return acc;
		}, ASSET_TYPES );
	
	return Object.values( countedTypes );
} )
</script>
